### PR TITLE
Add prerequisites

### PR DESCRIPTION
**Pull request by exced**
Hello there, awesome job on Revery !

I was trying to setup the project but it failed for missing dependencies. 
It could be helpful to mention `ragel` and `libpng` libs in the prerequisites section.

I saw it was added at some point in the revery package but maybe removed later on ? https://github.com/revery-ui/revery/pull/151

I also removed a duplicate line in the package.json, not sure if you wanted to keep it or not

### CODE REVIEW

**Comment by TheDahv** [comment]
@exced do you mind if we piggy back on here with our list for Ubuntu users? https://github.com/revery-ui/revery-quick-start/issues/40

**Comment by exced** [comment]
Sure we can have a troubleshooting section per OS maybe. Is this what you're thinking about ?

I had this issue on macOS

**Comment by TheDahv** [comment]
I suppose so! I moved on to another solution but I'm happy to help out.

**Review by glennsl — APPROVED** [review]
There's other dependencies needed as well, so I think I'm just going to refer to the requirements for revery, but merging this anyway since it's absolutely correct.

Thanks for the PR, and sorry it took so long to respond!

**Pull request merged**
